<?php

namespace App\Services;

class PublicUiTextCatalogService
{
    /**
     * @var array<string, array<string, string>>
     */
    private const TRANSLATIONS = [
        'en' => [
            'menu_language_label' => 'Menu language',
            'install_app' => 'Install app',
            'updated_at' => 'Updated',
            'categories_nav_label' => 'Menu categories',
            'all_items' => 'All items',
            'loading_menu' => 'Loading menu...',
            'menu_items_empty' => 'No menu items available.',
            'select_item' => 'Select',
            'item_unavailable' => 'Unavailable',
            'category_items_empty' => 'No items available in this category.',
            'selected_button' => 'Selected',
            'selected_items_heading' => 'Selected items',
            'show_waiter' => 'Show to the waiter',
            'close' => 'Close',
            'cart_empty' => 'Nothing selected yet.',
            'remove_item' => 'Remove',
            'remove_from_cart' => 'Remove from cart',
            'subtotal' => 'Subtotal',
            'total' => 'Total',
            'cart_bar_empty' => 'Cart is empty',
            'cart_bar_selected_count' => 'Selected items: {count}',
            'cart_bar_empty_caption' => 'Choose items',
            'cart_bar_ready_caption' => 'Show the order to the waiter',
            'extra_fee_default_label' => 'Extra fee',
            'updated_at_unknown' => 'Unknown',
            'decrease_quantity' => 'Decrease quantity',
            'increase_quantity' => 'Increase quantity',
            'load_menu_error' => 'Failed to load menu.',
            'uncategorized' => 'Others',
        ],
        'tr' => [
            'menu_language_label' => 'Menu dili',
            'install_app' => 'Uygulamayi yukle',
            'updated_at' => 'Guncellendi',
            'categories_nav_label' => 'Menu kategorileri',
            'all_items' => 'Tum yemekler',
            'loading_menu' => 'Menu yukleniyor...',
            'menu_items_empty' => 'Menude urun bulunmuyor.',
            'select_item' => 'Sec',
            'item_unavailable' => 'Mevcut degil',
            'category_items_empty' => 'Bu kategoride urun bulunmuyor.',
            'selected_button' => 'Secildi',
            'selected_items_heading' => 'Secilen yemekler',
            'show_waiter' => 'Garsona gosterin',
            'close' => 'Kapat',
            'cart_empty' => 'Henuz bir sey secilmedi.',
            'remove_item' => 'Kaldir',
            'remove_from_cart' => 'Sepetten kaldir',
            'subtotal' => 'Ara toplam',
            'total' => 'Toplam',
            'cart_bar_empty' => 'Sepet bos',
            'cart_bar_selected_count' => 'Secilenler: {count}',
            'cart_bar_empty_caption' => 'Yemekleri secin',
            'cart_bar_ready_caption' => 'Siparisi garsona gosterin',
            'extra_fee_default_label' => 'Ek ucret',
            'updated_at_unknown' => 'Bilinmiyor',
            'decrease_quantity' => 'Adedi azalt',
            'increase_quantity' => 'Adedi artir',
            'load_menu_error' => 'Menu yuklenemedi.',
            'uncategorized' => 'Diger',
        ],
        'ru' => [
            'menu_language_label' => 'Язык меню',
            'install_app' => 'Установить',
            'updated_at' => 'Обновлено',
            'categories_nav_label' => 'Категории меню',
            'all_items' => 'Все блюда',
            'loading_menu' => 'Загрузка меню...',
            'menu_items_empty' => 'Пункты меню отсутствуют.',
            'select_item' => 'Выбрать',
            'item_unavailable' => 'Недоступно',
            'category_items_empty' => 'В этой категории блюда отсутствуют.',
            'selected_button' => 'Выбрано',
            'selected_items_heading' => 'Выбранные блюда',
            'show_waiter' => 'Покажите официанту',
            'close' => 'Закрыть',
            'cart_empty' => 'Пока ничего не выбрано.',
            'remove_item' => 'Убрать',
            'remove_from_cart' => 'Убрать из корзины',
            'subtotal' => 'Подытог',
            'total' => 'Итого',
            'cart_bar_empty' => 'Корзина пуста',
            'cart_bar_selected_count' => 'Выбрано позиций: {count}',
            'cart_bar_empty_caption' => 'Выберите блюда',
            'cart_bar_ready_caption' => 'Покажите заказ официанту',
            'extra_fee_default_label' => 'Доп. сбор',
            'updated_at_unknown' => 'Неизвестно',
            'decrease_quantity' => 'Уменьшить',
            'increase_quantity' => 'Увеличить',
            'load_menu_error' => 'Не удалось загрузить меню.',
            'uncategorized' => 'Другое',
        ],
        'uz' => [
            'menu_language_label' => 'Menyu tili',
            'install_app' => 'Ilovani o\'rnatish',
            'updated_at' => 'Yangilandi',
            'categories_nav_label' => 'Menyu bo\'limlari',
            'all_items' => 'Barcha taomlar',
            'loading_menu' => 'Menyu yuklanmoqda...',
            'menu_items_empty' => 'Menyuda taomlar mavjud emas.',
            'select_item' => 'Tanlash',
            'item_unavailable' => 'Mavjud emas',
            'category_items_empty' => 'Bu bo\'limda taomlar mavjud emas.',
            'selected_button' => 'Tanlandi',
            'selected_items_heading' => 'Tanlangan taomlar',
            'show_waiter' => 'Ofitsiantga ko\'rsating',
            'close' => 'Yopish',
            'cart_empty' => 'Hali hech narsa tanlanmagan.',
            'remove_item' => 'Olib tashlash',
            'remove_from_cart' => 'Savatdan olib tashlash',
            'subtotal' => 'Oraliq jami',
            'total' => 'Jami',
            'cart_bar_empty' => 'Savat bo\'sh',
            'cart_bar_selected_count' => 'Tanlanganlar: {count}',
            'cart_bar_empty_caption' => 'Taomlarni tanlang',
            'cart_bar_ready_caption' => 'Buyurtmani ofitsiantga ko\'rsating',
            'extra_fee_default_label' => 'Qo\'shimcha to\'lov',
            'updated_at_unknown' => 'Noma\'lum',
            'decrease_quantity' => 'Kamaytirish',
            'increase_quantity' => 'Ko\'paytirish',
            'load_menu_error' => 'Menyuni yuklab bo\'lmadi.',
            'uncategorized' => 'Boshqalar',
        ],
        'ar' => [
            'menu_language_label' => 'لغة القائمة',
            'install_app' => 'تثبيت التطبيق',
            'updated_at' => 'تم التحديث',
            'categories_nav_label' => 'فئات القائمة',
            'all_items' => 'كل الأصناف',
            'loading_menu' => 'جار تحميل القائمة...',
            'menu_items_empty' => 'لا توجد أصناف في القائمة.',
            'select_item' => 'اختر',
            'item_unavailable' => 'غير متاح',
            'category_items_empty' => 'لا توجد أصناف في هذه الفئة.',
            'selected_button' => 'تم الاختيار',
            'selected_items_heading' => 'الأصناف المختارة',
            'show_waiter' => 'اعرضه على النادل',
            'close' => 'إغلاق',
            'cart_empty' => 'لم يتم اختيار أي شيء بعد.',
            'remove_item' => 'إزالة',
            'remove_from_cart' => 'إزالة من السلة',
            'subtotal' => 'المجموع الفرعي',
            'total' => 'الإجمالي',
            'cart_bar_empty' => 'السلة فارغة',
            'cart_bar_selected_count' => 'العناصر المختارة: {count}',
            'cart_bar_empty_caption' => 'اختر الأصناف',
            'cart_bar_ready_caption' => 'اعرض الطلب على النادل',
            'extra_fee_default_label' => 'رسوم إضافية',
            'updated_at_unknown' => 'غير معروف',
            'decrease_quantity' => 'تقليل الكمية',
            'increase_quantity' => 'زيادة الكمية',
            'load_menu_error' => 'تعذر تحميل القائمة.',
            'uncategorized' => 'أخرى',
        ],
        'zh' => [
            'menu_language_label' => '菜单语言',
            'install_app' => '安装应用',
            'updated_at' => '已更新',
            'categories_nav_label' => '菜单分类',
            'all_items' => '全部菜品',
            'loading_menu' => '正在加载菜单...',
            'menu_items_empty' => '暂无菜品。',
            'select_item' => '选择',
            'item_unavailable' => '不可用',
            'category_items_empty' => '该分类下暂无菜品。',
            'selected_button' => '已选',
            'selected_items_heading' => '已选菜品',
            'show_waiter' => '请给服务员查看',
            'close' => '关闭',
            'cart_empty' => '还没有选择任何菜品。',
            'remove_item' => '删除',
            'remove_from_cart' => '从购物车中移除',
            'subtotal' => '小计',
            'total' => '总计',
            'cart_bar_empty' => '购物车为空',
            'cart_bar_selected_count' => '已选菜品：{count}',
            'cart_bar_empty_caption' => '请选择菜品',
            'cart_bar_ready_caption' => '请向服务员出示订单',
            'extra_fee_default_label' => '附加费用',
            'updated_at_unknown' => '未知',
            'decrease_quantity' => '减少数量',
            'increase_quantity' => '增加数量',
            'load_menu_error' => '菜单加载失败。',
            'uncategorized' => '其他',
        ],
        'ko' => [
            'menu_language_label' => '메뉴 언어',
            'install_app' => '앱 설치',
            'updated_at' => '업데이트됨',
            'categories_nav_label' => '메뉴 카테고리',
            'all_items' => '모든 메뉴',
            'loading_menu' => '메뉴 불러오는 중...',
            'menu_items_empty' => '메뉴 항목이 없습니다.',
            'select_item' => '선택',
            'item_unavailable' => '이용 불가',
            'category_items_empty' => '이 카테고리에는 메뉴가 없습니다.',
            'selected_button' => '선택됨',
            'selected_items_heading' => '선택한 메뉴',
            'show_waiter' => '직원에게 보여주세요',
            'close' => '닫기',
            'cart_empty' => '아직 선택한 항목이 없습니다.',
            'remove_item' => '제거',
            'remove_from_cart' => '장바구니에서 제거',
            'subtotal' => '소계',
            'total' => '합계',
            'cart_bar_empty' => '장바구니가 비어 있습니다',
            'cart_bar_selected_count' => '선택한 항목: {count}',
            'cart_bar_empty_caption' => '메뉴를 선택하세요',
            'cart_bar_ready_caption' => '주문을 직원에게 보여주세요',
            'extra_fee_default_label' => '추가 요금',
            'updated_at_unknown' => '알 수 없음',
            'decrease_quantity' => '수량 줄이기',
            'increase_quantity' => '수량 늘리기',
            'load_menu_error' => '메뉴를 불러오지 못했습니다.',
            'uncategorized' => '기타',
        ],
        'ja' => [
            'menu_language_label' => 'メニュー言語',
            'install_app' => 'アプリをインストール',
            'updated_at' => '更新済み',
            'categories_nav_label' => 'メニューカテゴリ',
            'all_items' => 'すべての料理',
            'loading_menu' => 'メニューを読み込み中...',
            'menu_items_empty' => 'メニュー項目がありません。',
            'select_item' => '選択',
            'item_unavailable' => '利用不可',
            'category_items_empty' => 'このカテゴリには料理がありません。',
            'selected_button' => '選択済み',
            'selected_items_heading' => '選択した料理',
            'show_waiter' => '店員にお見せください',
            'close' => '閉じる',
            'cart_empty' => 'まだ何も選択されていません。',
            'remove_item' => '削除',
            'remove_from_cart' => 'カートから削除',
            'subtotal' => '小計',
            'total' => '合計',
            'cart_bar_empty' => 'カートは空です',
            'cart_bar_selected_count' => '選択中の品目: {count}',
            'cart_bar_empty_caption' => '料理を選択してください',
            'cart_bar_ready_caption' => '注文を店員に見せてください',
            'extra_fee_default_label' => '追加料金',
            'updated_at_unknown' => '不明',
            'decrease_quantity' => '数量を減らす',
            'increase_quantity' => '数量を増やす',
            'load_menu_error' => 'メニューを読み込めませんでした。',
            'uncategorized' => 'その他',
        ],
        'es' => [
            'menu_language_label' => 'Idioma del menu',
            'install_app' => 'Instalar app',
            'updated_at' => 'Actualizado',
            'categories_nav_label' => 'Categorias del menu',
            'all_items' => 'Todos los platos',
            'loading_menu' => 'Cargando menu...',
            'menu_items_empty' => 'No hay platos disponibles.',
            'select_item' => 'Seleccionar',
            'item_unavailable' => 'No disponible',
            'category_items_empty' => 'No hay platos en esta categoria.',
            'selected_button' => 'Seleccionado',
            'selected_items_heading' => 'Platos seleccionados',
            'show_waiter' => 'Muestrelo al camarero',
            'close' => 'Cerrar',
            'cart_empty' => 'Aun no has seleccionado nada.',
            'remove_item' => 'Quitar',
            'remove_from_cart' => 'Quitar del carrito',
            'subtotal' => 'Subtotal',
            'total' => 'Total',
            'cart_bar_empty' => 'El carrito esta vacio',
            'cart_bar_selected_count' => 'Platos seleccionados: {count}',
            'cart_bar_empty_caption' => 'Elige platos',
            'cart_bar_ready_caption' => 'Muestra el pedido al camarero',
            'extra_fee_default_label' => 'Cargo adicional',
            'updated_at_unknown' => 'Desconocido',
            'decrease_quantity' => 'Disminuir cantidad',
            'increase_quantity' => 'Aumentar cantidad',
            'load_menu_error' => 'No se pudo cargar el menu.',
            'uncategorized' => 'Otros',
        ],
        'de' => [
            'menu_language_label' => 'Menusprache',
            'install_app' => 'App installieren',
            'updated_at' => 'Aktualisiert',
            'categories_nav_label' => 'Menukategorien',
            'all_items' => 'Alle Gerichte',
            'loading_menu' => 'Menu wird geladen...',
            'menu_items_empty' => 'Keine Menupunkte verfugbar.',
            'select_item' => 'Auswahlen',
            'item_unavailable' => 'Nicht verfugbar',
            'category_items_empty' => 'In dieser Kategorie gibt es keine Gerichte.',
            'selected_button' => 'Ausgewahlt',
            'selected_items_heading' => 'Ausgewahlte Gerichte',
            'show_waiter' => 'Zeigen Sie es dem Kellner',
            'close' => 'Schliessen',
            'cart_empty' => 'Noch nichts ausgewahlt.',
            'remove_item' => 'Entfernen',
            'remove_from_cart' => 'Aus dem Warenkorb entfernen',
            'subtotal' => 'Zwischensumme',
            'total' => 'Gesamt',
            'cart_bar_empty' => 'Der Warenkorb ist leer',
            'cart_bar_selected_count' => 'Ausgewahlte Artikel: {count}',
            'cart_bar_empty_caption' => 'Gerichte auswahlen',
            'cart_bar_ready_caption' => 'Zeigen Sie die Bestellung dem Kellner',
            'extra_fee_default_label' => 'Zusatzliche Gebuhr',
            'updated_at_unknown' => 'Unbekannt',
            'decrease_quantity' => 'Menge verringern',
            'increase_quantity' => 'Menge erhohen',
            'load_menu_error' => 'Menu konnte nicht geladen werden.',
            'uncategorized' => 'Sonstiges',
        ],
        'fa' => [
            'menu_language_label' => 'زبان منو',
            'install_app' => 'نصب برنامه',
            'updated_at' => 'به‌روزرسانی شد',
            'categories_nav_label' => 'دسته‌بندی‌های منو',
            'all_items' => 'همه غذاها',
            'loading_menu' => 'در حال بارگذاری منو...',
            'menu_items_empty' => 'موردی در منو وجود ندارد.',
            'select_item' => 'انتخاب',
            'item_unavailable' => 'ناموجود',
            'category_items_empty' => 'در این دسته‌بندی غذایی وجود ندارد.',
            'selected_button' => 'انتخاب شده',
            'selected_items_heading' => 'غذاهای انتخاب‌شده',
            'show_waiter' => 'به گارسون نشان دهید',
            'close' => 'بستن',
            'cart_empty' => 'هنوز چیزی انتخاب نشده است.',
            'remove_item' => 'حذف',
            'remove_from_cart' => 'حذف از سبد',
            'subtotal' => 'جمع جزء',
            'total' => 'جمع کل',
            'cart_bar_empty' => 'سبد خالی است',
            'cart_bar_selected_count' => 'موارد انتخاب‌شده: {count}',
            'cart_bar_empty_caption' => 'غذاها را انتخاب کنید',
            'cart_bar_ready_caption' => 'سفارش را به گارسون نشان دهید',
            'extra_fee_default_label' => 'هزینه اضافی',
            'updated_at_unknown' => 'نامشخص',
            'decrease_quantity' => 'کاهش تعداد',
            'increase_quantity' => 'افزایش تعداد',
            'load_menu_error' => 'بارگیری منو انجام نشد.',
            'uncategorized' => 'سایر',
        ],
        'fr' => [
            'menu_language_label' => 'Langue du menu',
            'install_app' => 'Installer l\'application',
            'updated_at' => 'Mis a jour',
            'categories_nav_label' => 'Categories du menu',
            'all_items' => 'Tous les plats',
            'loading_menu' => 'Chargement du menu...',
            'menu_items_empty' => 'Aucun plat disponible.',
            'select_item' => 'Choisir',
            'item_unavailable' => 'Indisponible',
            'category_items_empty' => 'Aucun plat dans cette categorie.',
            'selected_button' => 'Selectionne',
            'selected_items_heading' => 'Plats selectionnes',
            'show_waiter' => 'Montrez-le au serveur',
            'close' => 'Fermer',
            'cart_empty' => 'Rien n\'a encore ete selectionne.',
            'remove_item' => 'Retirer',
            'remove_from_cart' => 'Retirer du panier',
            'subtotal' => 'Sous-total',
            'total' => 'Total',
            'cart_bar_empty' => 'Le panier est vide',
            'cart_bar_selected_count' => 'Articles selectionnes : {count}',
            'cart_bar_empty_caption' => 'Choisissez des plats',
            'cart_bar_ready_caption' => 'Montrez la commande au serveur',
            'extra_fee_default_label' => 'Frais supplementaires',
            'updated_at_unknown' => 'Inconnu',
            'decrease_quantity' => 'Diminuer la quantite',
            'increase_quantity' => 'Augmenter la quantite',
            'load_menu_error' => 'Impossible de charger le menu.',
            'uncategorized' => 'Autres',
        ],
        'pt' => [
            'menu_language_label' => 'Idioma do menu',
            'install_app' => 'Instalar app',
            'updated_at' => 'Atualizado',
            'categories_nav_label' => 'Categorias do menu',
            'all_items' => 'Todos os pratos',
            'loading_menu' => 'A carregar menu...',
            'menu_items_empty' => 'Nao ha pratos disponiveis.',
            'select_item' => 'Selecionar',
            'item_unavailable' => 'Indisponivel',
            'category_items_empty' => 'Nao ha pratos nesta categoria.',
            'selected_button' => 'Selecionado',
            'selected_items_heading' => 'Pratos selecionados',
            'show_waiter' => 'Mostre ao empregado',
            'close' => 'Fechar',
            'cart_empty' => 'Ainda nao selecionou nada.',
            'remove_item' => 'Remover',
            'remove_from_cart' => 'Remover do carrinho',
            'subtotal' => 'Subtotal',
            'total' => 'Total',
            'cart_bar_empty' => 'O carrinho esta vazio',
            'cart_bar_selected_count' => 'Itens selecionados: {count}',
            'cart_bar_empty_caption' => 'Escolha os pratos',
            'cart_bar_ready_caption' => 'Mostre o pedido ao empregado',
            'extra_fee_default_label' => 'Taxa adicional',
            'updated_at_unknown' => 'Desconhecido',
            'decrease_quantity' => 'Diminuir quantidade',
            'increase_quantity' => 'Aumentar quantidade',
            'load_menu_error' => 'Nao foi possivel carregar o menu.',
            'uncategorized' => 'Outros',
        ],
        'it' => [
            'menu_language_label' => 'Lingua del menu',
            'install_app' => 'Installa app',
            'updated_at' => 'Aggiornato',
            'categories_nav_label' => 'Categorie del menu',
            'all_items' => 'Tutti i piatti',
            'loading_menu' => 'Caricamento menu...',
            'menu_items_empty' => 'Nessun piatto disponibile.',
            'select_item' => 'Seleziona',
            'item_unavailable' => 'Non disponibile',
            'category_items_empty' => 'Nessun piatto in questa categoria.',
            'selected_button' => 'Selezionato',
            'selected_items_heading' => 'Piatti selezionati',
            'show_waiter' => 'Mostralo al cameriere',
            'close' => 'Chiudi',
            'cart_empty' => 'Non hai ancora selezionato nulla.',
            'remove_item' => 'Rimuovi',
            'remove_from_cart' => 'Rimuovi dal carrello',
            'subtotal' => 'Subtotale',
            'total' => 'Totale',
            'cart_bar_empty' => 'Il carrello e vuoto',
            'cart_bar_selected_count' => 'Piatti selezionati: {count}',
            'cart_bar_empty_caption' => 'Scegli i piatti',
            'cart_bar_ready_caption' => 'Mostra l\'ordine al cameriere',
            'extra_fee_default_label' => 'Costo aggiuntivo',
            'updated_at_unknown' => 'Sconosciuto',
            'decrease_quantity' => 'Riduci quantita',
            'increase_quantity' => 'Aumenta quantita',
            'load_menu_error' => 'Impossibile caricare il menu.',
            'uncategorized' => 'Altro',
        ],
        'hi' => [
            'menu_language_label' => 'मेन्यू भाषा',
            'install_app' => 'ऐप इंस्टॉल करें',
            'updated_at' => 'अपडेट किया गया',
            'categories_nav_label' => 'मेन्यू श्रेणियां',
            'all_items' => 'सभी व्यंजन',
            'loading_menu' => 'मेन्यू लोड हो रहा है...',
            'menu_items_empty' => 'कोई मेन्यू आइटम उपलब्ध नहीं हैं.',
            'select_item' => 'चुनें',
            'item_unavailable' => 'उपलब्ध नहीं',
            'category_items_empty' => 'इस श्रेणी में कोई व्यंजन उपलब्ध नहीं हैं.',
            'selected_button' => 'चुना गया',
            'selected_items_heading' => 'चुने गए व्यंजन',
            'show_waiter' => 'वेटर को दिखाएं',
            'close' => 'बंद करें',
            'cart_empty' => 'अभी तक कुछ भी नहीं चुना गया है.',
            'remove_item' => 'हटाएं',
            'remove_from_cart' => 'कार्ट से हटाएं',
            'subtotal' => 'उप-योग',
            'total' => 'कुल',
            'cart_bar_empty' => 'कार्ट खाली है',
            'cart_bar_selected_count' => 'चुने गए आइटम: {count}',
            'cart_bar_empty_caption' => 'व्यंजन चुनें',
            'cart_bar_ready_caption' => 'ऑर्डर वेटर को दिखाएं',
            'extra_fee_default_label' => 'अतिरिक्त शुल्क',
            'updated_at_unknown' => 'अज्ञात',
            'decrease_quantity' => 'मात्रा घटाएं',
            'increase_quantity' => 'मात्रा बढ़ाएं',
            'load_menu_error' => 'मेन्यू लोड नहीं हो सका.',
            'uncategorized' => 'अन्य',
        ],
    ];

    public function __construct(
        private readonly LanguageCatalogService $languageCatalog = new LanguageCatalogService(),
    ) {
    }

    /**
     * @return array<string, array<string, string>>
     */
    public function getSupportedTranslationsIndexed(): array
    {
        return self::TRANSLATIONS;
    }

    /**
     * @return array<string, string>|null
     */
    public function getTranslationsForLanguage(string $languageCode): ?array
    {
        $normalizedCode = strtolower(trim($languageCode));

        if ($normalizedCode === '' || ! $this->languageCatalog->isSupported($normalizedCode)) {
            return null;
        }

        return self::TRANSLATIONS[$normalizedCode] ?? null;
    }

    /**
     * @param list<string> $languageCodes
     *
     * @return array<string, array<string, string>>
     */
    public function getTranslationsForLanguages(array $languageCodes): array
    {
        $translations = [];

        foreach ($languageCodes as $languageCode) {
            $normalizedCode = strtolower(trim((string) $languageCode));

            if ($normalizedCode === '' || array_key_exists($normalizedCode, $translations)) {
                continue;
            }

            $translation = $this->getTranslationsForLanguage($normalizedCode);

            if ($translation !== null) {
                $translations[$normalizedCode] = $translation;
            }
        }

        return $translations;
    }
}
